Repository Bogdan-Zinovij/Ecstasify, pull requests merged in 2023-01, with the labels that each got.

#59 Feat/#39/implement user auth
  helm/Chart.lock
  helm/values.yaml
  services/users/.env
  services/users/.env.example
  services/users/.eslintrc.json
  services/users/.gitignore
  services/users/.prettierrc.json
  services/users/README.md
  services/users/migrations/20221030101907_spending_init.down.sql
  services/users/migrations/20221030101907_spending_init.up.sql
  services/users/migrations/Dockerfile
  services/users/package-lock.json
  services/users/package.json
  services/users/src/app.js
  services/users/src/config.js
  services/users/src/controllers/auth.controller.js
  services/users/src/controllers/user.controller.js
  services/users/src/controllers/userController.js
  services/users/src/db/associate.js
  services/users/src/db/database.json
  services/users/src/db/db.js
  services/users/src/db/migrations/20221030101907_spending_init.down.sql
  services/users/src/db/migrations/20221030101907_spending_init.up.sql
  services/users/src/db/migrations/Dockerfile
  services/users/src/db/models/token.model.js
  services/users/src/db/models/user.model.js
  services/users/src/dtos/user.dto.js
  services/users/src/middlewares/auth/auth.middleware.js
  services/users/src/middlewares/auth/permission.middleware.js
  services/users/src/middlewares/validation/auth.validation.js
  services/users/src/middlewares/validation/user.validation.js
  services/users/src/routers/auth.router.js
  services/users/src/routers/user.router.js
  services/users/src/server.js
  services/users/src/services/auth.service.js
  services/users/src/services/kafka-notification-producer.service.js
  services/users/src/services/token.service.js
  services/users/src/services/user.service.js
  services/users/src/services/userServices.js
Labels: feature

#72 Feat/#39/implement user auth
  services/users/src/controllers/user.controller.js
  services/users/src/middlewares/validation/user.validation.js
  services/users/src/routers/user.router.js
  services/users/src/services/auth.service.js
  services/users/src/services/user.service.js
Labels: feature

#74 add kafka notification producer/consumer in 'users' service
  services/users/src/config.js
  services/users/src/dtos/user-notification.dto.js
  services/users/src/services/auth.service.js
  services/users/src/services/kafka-notification-consumer.service.js
  services/users/src/services/kafka-notification-producer.service.js
Labels: feature

#81 feat(subscriptions): #67 Implement subscriptions service
  services/subscriptions/.env.example
  services/subscriptions/.gitignore
  services/subscriptions/docker-compose.yml
  services/subscriptions/package-lock.json
  services/subscriptions/package.json
  services/subscriptions/src/app.module.ts
  services/subscriptions/src/common/dto/id.dto.ts
  services/subscriptions/src/common/dto/index.ts
  services/subscriptions/src/common/entities/base-entity-with-id.entity.ts
  services/subscriptions/src/common/entities/index.ts
  services/subscriptions/src/common/enums/error-messages.enum.ts
  services/subscriptions/src/common/index.ts
  services/subscriptions/src/common/interfaces/index.ts
  services/subscriptions/src/common/interfaces/service-error-messages.interface.ts
  services/subscriptions/src/common/services/base.service.ts
  services/subscriptions/src/common/services/index.ts
  services/subscriptions/src/common/types/id.type.ts
  services/subscriptions/src/common/types/index.ts
  services/subscriptions/src/database/database.module.ts
  services/subscriptions/src/database/migrations/20221030231112_init.down.sql
  services/subscriptions/src/database/migrations/20221030231112_init.up.sql
  services/subscriptions/src/main.ts
  services/subscriptions/src/modules/subscriptions/controllers/features.controller.ts
  services/subscriptions/src/modules/subscriptions/controllers/subscription-features.controller.ts
  services/subscriptions/src/modules/subscriptions/dto/features/create-feature.dto.ts
  services/subscriptions/src/modules/subscriptions/dto/features/index.ts
  services/subscriptions/src/modules/subscriptions/dto/features/update-feature.dto.ts
  services/subscriptions/src/modules/subscriptions/dto/index.ts
  services/subscriptions/src/modules/subscriptions/dto/subscription-features/create-subscription-feature.dto.ts
  services/subscriptions/src/modules/subscriptions/dto/subscription-features/index.ts
  services/subscriptions/src/modules/subscriptions/dto/subscription-features/update-subscription-feature.dto.ts
  services/subscriptions/src/modules/subscriptions/dto/subscription-plans/create-subscription-plan.dto.ts
  services/subscriptions/src/modules/subscriptions/dto/subscription-plans/index.ts
  services/subscriptions/src/modules/subscriptions/dto/subscription-plans/update-subscription-plan.dto.ts
  services/subscriptions/src/modules/subscriptions/entities/feature.entity.ts
  services/subscriptions/src/modules/subscriptions/entities/index.ts
  services/subscriptions/src/modules/subscriptions/entities/subscription-feature.entity.ts
  services/subscriptions/src/modules/subscriptions/entities/subscription-plan.entity.ts
  services/subscriptions/src/modules/subscriptions/services/features.service.ts
  services/subscriptions/src/modules/subscriptions/services/subscription-features.service.ts
  services/subscriptions/src/modules/subscriptions/services/subscription-plans.service.ts
  services/subscriptions/src/modules/subscriptions/subscriptions.module.ts
Labels: feature

#89 Fix/#78/fix consumer producer issues
  helm/values.yaml
  services/authors/src/db/migrations/Dockerfile
  services/notifications/src/main.ts
  services/notifications/src/modules/kafka/dto/handle-new-track-created.dto.ts
  services/notifications/src/modules/kafka/dto/index.ts
  services/notifications/src/modules/kafka/enums/topic.enum.ts
  services/notifications/src/modules/kafka/kafka.controller.ts
  services/notifications/src/modules/kafka/kafka.service.ts
  services/tracks/src/services/trackService.js
  services/users/src/config.js
  services/users/src/middlewares/auth/auth.middleware.js
  services/users/src/middlewares/auth/permission.middleware.js
  services/users/src/services/auth.service.js
  services/users/src/services/kafka-notification-consumer.service.js
  services/users/src/services/kafka-notification-producer.service.js
Labels: bug

#84 Refactor/#83/users service error handling
  services/notifications.rar
  services/users/src/config.js
  services/users/src/controllers/auth.controller.js
  services/users/src/controllers/user.controller.js
  services/users/src/errors-handling/convert-err-to-http-form.js
  services/users/src/errors-handling/custom-errors.js
  services/users/src/middlewares/auth/auth.middleware.js
  services/users/src/middlewares/auth/permission.middleware.js
  services/users/src/services/auth.service.js
  services/users/src/services/user.service.js
Labels: refactoring

#92 feat(files): #85 Implement files service
  helm/charts/files/Chart.lock
  helm/charts/files/Chart.yaml
  helm/charts/files/templates/config-map.yaml
  helm/charts/files/templates/deployment.yaml
  helm/charts/files/templates/ingress.yaml
  helm/charts/files/templates/secret.yaml
  helm/charts/files/templates/service.yaml
  helm/charts/files/values.yaml
  services/files/.env.example
  services/files/.eslintrc.js
  services/files/.gitignore
  services/files/.prettierrc
  services/files/Dockerfile
  services/files/README.md
  services/files/docker-compose.yml
  services/files/nest-cli.json
  services/files/package-lock.json
  services/files/package.json
  services/files/src/app.module.ts
  services/files/src/common/dto/id.dto.ts
  services/files/src/common/dto/index.ts
  services/files/src/common/enums/error-messages.enum.ts
  services/files/src/common/enums/index.ts
  services/files/src/common/index.ts
  services/files/src/database/database.module.ts
  services/files/src/database/migrations/.dockerignore
  services/files/src/database/migrations/20221030231223_init.down.sql
  services/files/src/database/migrations/20221030231223_init.up.sql
  services/files/src/database/migrations/Dockerfile
  services/files/src/main.ts
  services/files/src/modules/files/entities/file.entity.ts
  services/files/src/modules/files/entities/index.ts
  services/files/src/modules/files/files.constants.ts
  services/files/src/modules/files/files.controller.ts
  services/files/src/modules/files/files.module.ts
  services/files/src/modules/files/files.service.ts
  services/files/tsconfig.build.json
  services/files/tsconfig.json
Labels: feature

#100 refctor: #99 Refactor notifications files subscriptions
  services/files/src/modules/files/files.service.ts
  services/notifications/.env.example
  services/notifications/src/modules/kafka/interfaces/index.ts
  services/notifications/src/modules/kafka/interfaces/kafka-message.interface.ts
  services/subscriptions/src/modules/subscriptions/entities/feature.entity.ts
  services/subscriptions/src/modules/subscriptions/entities/subscription-feature.entity.ts
  services/subscriptions/src/modules/subscriptions/entities/subscription-plan.entity.ts
Labels: refactoring

#104 Refactor/#98/users service
  services/users/src/config.js
  services/users/src/controllers/auth.controller.js
  services/users/src/errors-handling/convert-err-to-http-form.js
  services/users/src/middlewares/validation/auth.validation.js
  services/users/src/middlewares/validation/user.validation.js
  services/users/src/services/token.service.js
Labels: refactoring

#108 Create LICENSE.md
  LICENSE.md
Labels: documentation

#110 Docs/#109/update readme
  README.md
Labels: documentation

#111 Docs/#109/update readme
  README.md
Labels: documentation

#117 remove unnecessary section from readme
  README.md
Labels: documentation

#120 Refactor/#118/refactor authors service
  services/authors/src/config.js
  services/authors/src/controllers/author.controller.js
  services/authors/src/errors-handling/convert-err-to-http-form.js
  services/authors/src/errors-handling/custom-errors.js
  services/authors/src/middlewares/author.validation.js
  services/authors/src/services/author.service.js
  services/users/src/services/user.service.js
Labels: refactoring

#123 Backend/dev
  services/authors/src/config.js
  services/authors/src/controllers/author.controller.js
  services/authors/src/errors-handling/convert-err-to-http-form.js
  services/authors/src/errors-handling/custom-errors.js
  services/authors/src/middlewares/author.validation.js
  services/authors/src/services/author.service.js
  services/users/src/services/user.service.js
Labels: refactoring

#125 Dev
  services/authors/src/config.js
  services/authors/src/controllers/author.controller.js
  services/authors/src/errors-handling/convert-err-to-http-form.js
  services/authors/src/errors-handling/custom-errors.js
  services/authors/src/middlewares/author.validation.js
  services/authors/src/services/author.service.js
  services/users/src/services/user.service.js
Labels: refactoring

#129 Refactor/#128/validation check middleware
  services/authors/src/config.js
  services/authors/src/controllers/author.controller.js
  services/authors/src/middlewares/validate-request.js
  services/authors/src/routers/author.router.js
  services/users/src/config.js
  services/users/src/controllers/auth.controller.js
  services/users/src/controllers/user.controller.js
  services/users/src/middlewares/validation/validate-request.js
  services/users/src/routers/auth.router.js
  services/users/src/routers/user.router.js
Labels: refactoring

#130 Add middleware for handling validation errors (authors, users services)
  services/authors/src/config.js
  services/authors/src/controllers/author.controller.js
  services/authors/src/middlewares/validate-request.js
  services/authors/src/routers/author.router.js
  services/users/src/config.js
  services/users/src/controllers/auth.controller.js
  services/users/src/controllers/user.controller.js
  services/users/src/middlewares/validation/validate-request.js
  services/users/src/routers/auth.router.js
  services/users/src/routers/user.router.js
Labels: refactoring

#131 Add middleware for handling validation errors (authors, users services)
  services/authors/src/config.js
  services/authors/src/controllers/author.controller.js
  services/authors/src/middlewares/validate-request.js
  services/authors/src/routers/author.router.js
  services/users/src/config.js
  services/users/src/controllers/auth.controller.js
  services/users/src/controllers/user.controller.js
  services/users/src/middlewares/validation/validate-request.js
  services/users/src/routers/auth.router.js
  services/users/src/routers/user.router.js
Labels: refactoring

#133 refactor(tracks): move axios config values to constants
  services/tracks/src/config.js
  services/tracks/src/config/axios.config.js
Labels: refactoring

#134 refactor(tracks): move axios config values to constants
  services/tracks/src/config.js
  services/tracks/src/config/axios.config.js
Labels: refactoring

#135 refactor(tracks): move axios config values to constants #133
  services/tracks/src/config.js
  services/tracks/src/config/axios.config.js
Labels: refactoring

#137 refactor(playlists): move axios config values to constants in playlis…
  services/playlists/src/config.js
  services/playlists/src/config/axios.config.js
Labels: refactoring

#138 refactor(playlists): move axios config values to constants
  services/playlists/src/config.js
  services/playlists/src/config/axios.config.js
Labels: refactoring

#139 refactor(playlists): move axios config values to constants
  services/playlists/src/config.js
  services/playlists/src/config/axios.config.js
Labels: refactoring
